DS_AUGMENTS_CFG:
- name: CropPtsAug
  p_apply_extra_tensors:
  - false
  - false
  p_crop_ratio: 1
  p_max_pts: 1500
  p_prob: 0.0
- name: RotationAug
  p_apply_extra_tensors:
  - false
  - false
  p_axis: 1
  p_max_angle: 6.28318530718
  p_min_angle: 0.0
  p_prob: 0.0
- name: RotationAug
  p_apply_extra_tensors:
  - false
  - false
  p_axis: 0
  p_max_angle: 0.1308996939
  p_min_angle: -0.1308996939
  p_prob: 0.0
- name: RotationAug
  p_apply_extra_tensors:
  - false
  - false
  p_axis: 2
  p_max_angle: 0.1308996939
  p_min_angle: -0.1308996939
  p_prob: 0.0
- name: NoiseAug
  p_apply_extra_tensors:
  - false
  - false
  p_clip: 0.02
  p_prob: 0.0
  p_stddev: 0.005
- name: LinearAug
  p_apply_extra_tensors:
  - false
  - false
  p_channel_independent: true
  p_max_a: 1.1
  p_max_b: 0.0
  p_min_a: 0.9
  p_min_b: 0.0
  p_prob: 0.0
- name: MirrorAug
  p_apply_extra_tensors:
  - false
  - false
  p_axes:
  - true
  - true
  - false
  p_mirror_prob: 0.5
  p_prob: 0.0
batch_size: 14
clip_len: 24
data_test_path: /data/iballester/datasets/BAD2/f_depth_npz_0-8_7
data_train_path: /data/iballester/datasets/BAD2/f_depth_npz_0-8_7
dataset: BAD2
dataset_root: /data/iballester/datasets/BAD2
depth: 5
device_args: 3,4,5
dim: 1024
dim_head: 128
emb_relu: false
epochs: 1
frame_interval: 1
heads: 8
log_dir: log
loss_type: weighted_cross_entropy
lr: 0.0346040836353532
lr_gamma: 0.1
lr_milestones:
- 20
- 30
lr_warmup_epochs: 10
max_frame_interval: 20
mlp_dim: 2048
model: P4Transformer
momentum: 0.9
n_trials: 2
nsamples: 32
num_points: 2048
output_dir: /caa/Homes01/iballester/dev-svr/ar4pc_ev/hyper_experiments/P4T_BAD2/1/log
radius: 0.7
resume: ''
save: true
seed: 0
spatial_stride: 32
split: /sets_0-8_7_val.txt
split_test_path: /data/iballester/datasets/BAD2/sets_0-8_7_val.txt
split_train_path: /data/iballester/datasets/BAD2/sets_0-8_7_val.txt
start_epoch: 0
temporal_kernel_size: 3
temporal_stride: 2
val_set: true
wandb_active: false
wandb_project: hyper_BAD2
weight_decay: 2.7188272817213995e-08
workers: 16
